contributing.md, website/contributing/index.html
=> update contributing guide

.github/scripts/merge_csv_to_topojson.py, .github/workflows/merge-csv-to-topojson.yml, .gitignore
- moves python script to .github directory
- also cleans up .gitignore
- prepares for #18 and #34
=> add github action scripts

.github/workflows/merge-csv-to-topojson.yml
=> fix workflow for merging csv to topojson

contributing.md, website/contributing/index.html
fixes #44 - make it clearer which issues to look at.
Also fixes a typo.
=> update contributing pages

.github/workflows/minify-map-json.yml
=> fix filepath in action

.github/scripts/minify-map-json.sh, .github/workflows/minify-map-json.yml
- apparently it needs sudo with no password to npm install?
- also added ability to run the json update action manually
=> update github action

.github/scripts/minify-map-json.sh, .github/workflows/minify-map-json.yml
- update yml by bringing shell script into the main action yml
- add shebang to shell script file in case this doesn't work and we need it still
=> reconfigure minify-map-json action

.github/workflows/minify-map-json.yml
yet another attempt to fix actions.
=> change login in Actions filter

website/data/library_services_information.csv
=> update armadale libraries info

.github/workflows/automerge.yml
=> PR check action

website/data/public_library_locations.csv
=> fix rockhampton ghost library, titlecase library names, collapse excess whitespace

.github/scripts/contributors.js, .github/workflows/add-contributors.yml, .gitignore, README.md, about.md, contributors.txt, sources.md, website/about/index.html, website/sources/index.html
- updates various pages
- adds Action to update contributors as needed.
=> Contributors

.github/scripts/contributors.js, .github/workflows/minify-map-json.yml
Fixes auto-commiter name problem, and ACT naming regression.
=> Auto commit fix

contributing.md
Fixes #100 - a few minor typos
=> fix typos in contributing.md

website/load-map.js
- creates BaseMap constructor for all base map tile layers
- creates LocationsLayer constructor for all location layers
- replaces old verbose code with more succinct code using these constructors
=> make code more DRY

website/data/library_services_information.csv
=> fix hornsby typo

fines.md, website/about/index.html, website/contributing/index.html, website/data/library_services_information.csv, website/data/public_library_locations.csv, website/fines/index.html, website/index.html, website/sources/index.html
- updated Port Hedland info
- add Fines page to website
=> Fines & Port Hedland

website/data/library_services_information.csv
=> Corangamite

contributing.md, website/contributing/index.html, website/data/library_services_information.csv, website/data/nsla_library_locations.csv, website/load-map.js
=> nsla overlay

.gitignore, website/data/library_services_information.csv
=> geelong fine free

website/data/library_services_information.csv, website/data/nsla_library_locations.csv, website/load-map.js
- change SLV to Alma
- change Newcastle regional to iii Polaris
- add Polaris as a colour option on the map
=> ILS updates

website/data/library_services_information.csv
=> just a test to trigger bot

website/data/academic_library_locations.csv, website/load-map.js
- academic libraries added
- discovery index info added for academic libraries popup
fixes #166
=> add academic libraries

website/data/public_library_locations.csv
Thanks to Sam Campbell for this info.
=> update and add new Ipswich branches

website/data/academic_library_locations.csv
=> Various updates to academic library ILS data

website/data/nsla_library_locations.csv, website/load-map.js
=> FOLIO at NLA

website/load-map.js
Also fixes nsla libraries showing "undefined" for discovery layer
=> fixes #174

website/data/library_services_information.csv
=> update GLRC ILS

website/data/library_services_information.csv, website/who-else/index.html
=> Moonee Valley free and fix Edge error
